# Generated by Django 3.1.2 on 2020-10-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
    ]
