# Generated by Django 3.1.2 on 2020-10-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
    ]
